### ISSUE TITLE
has an issue about permission access

### ISSUE THREAD

**Issue by dengminxue** [PrahlM93/ADReset#26]
You do not have permission to use ADReset. Please contact the Help Desk for assistance.

**Comment by mprahl** [comment]
Hi @dengminxue, you'll need to reach out to whoever is running ADReset at your organization. This is where the code is developed.

**Comment by dengminxue** [comment]
Thanks mprahl, The user has this issue when login for change password

**Comment by mprahl** [comment]
@dengminxue did you configure ADReset's "Reset Capable Security Groups" with a security group that the user is a member of?

Here is a screenshot of it:
https://github.com/mprahl/ADReset/blob/master/screenshots/6%20System%20Settings%201.jpg

**Comment by dengminxue** [comment]
yes, I set it for domain users

**Comment by dengminxue** [comment]
It's ok, Thank you very much
